packages:
  - Backend/*
  - Frontend/*
  - Libraries/@YD/*

catalogs:
  backend:
    # Core
    express: ^5.2.1
    dotenv: ^17.2.3
    cors: ^2.8.5
    helmet: ^8.1.0

    # Database
    mysql2: ^3.12.0

    # Auth
    jsonwebtoken: ^9.0.2
    bcryptjs: ^2.4.3

    # File Upload
    multer: ^1.4.5-lts.1

    # CSV Export
    csv-stringify: ^6.5.2

    # Utilities
    uuid: ^11.1.0
    axios: ^1.7.9

     # Gateway
    http-proxy-middleware: ^3.0.3
    express-rate-limit: ^7.5.0

    # Types
    "@types/node": ^22.13.1
    "@types/express": ^5.0.6
    "@types/cors": ^2.8.17
    "@types/jsonwebtoken": ^9.0.7
    "@types/bcryptjs": ^2.4.6
    "@types/multer": ^1.4.12
    "@types/uuid": ^10.0.0

    # Dev Tools
    typescript: ^5.7.3
    ts-node: ^10.9.2
    nodemon: ^3.1.9

